spring.application.name=SpringSecurity

spring.security.user.name=alam
spring.security.user.password=0000

spring.datasource.url=jdbc:postgresql://localhost:5432/Security
spring.datasource.username=postgres
spring.datasource.password=0000

spring.jpa.hibernate.ddl-auto=update